//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapTGDD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaChi_TGDD
    {
        public int MaDC { get; set; }
        public string TenDC { get; set; }
        public System.Data.Spatial.DbGeometry ToaDo { get; set; }
        public string MaQH { get; set; }
    
        public virtual QuanHuyen QuanHuyen { get; set; }
    }
}
