//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapTGDD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        public string MaND { get; set; }
        public string Ho { get; set; }
        public string Ten { get; set; }
        public string MatKhau { get; set; }
        public string MaQH { get; set; }
    
        public virtual QuanHuyen QuanHuyen { get; set; }
    }
}
