//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapTGDD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuanHuyen
    {
        public QuanHuyen()
        {
            this.DiaChi_TGDD = new HashSet<DiaChi_TGDD>();
            this.NguoiDungs = new HashSet<NguoiDung>();
        }
    
        public string MaQH { get; set; }
        public string TenQH { get; set; }
        public string MaTinh { get; set; }
    
        public virtual ICollection<DiaChi_TGDD> DiaChi_TGDD { get; set; }
        public virtual ICollection<NguoiDung> NguoiDungs { get; set; }
        public virtual Tinh Tinh { get; set; }
    }
}
