//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MapTGDD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tinh
    {
        public Tinh()
        {
            this.QuanHuyens = new HashSet<QuanHuyen>();
        }
    
        public string MaTinh { get; set; }
        public string TenTinh { get; set; }
    
        public virtual ICollection<QuanHuyen> QuanHuyens { get; set; }
    }
}
